FORMAT: 1A

# Courses API
Notes API is a *short texts saving* service similar to its physical paper presence on your table.

# Group Notes
Notes related resources of the **Notes API**

## Notes Collection [/notes]
### List all Notes [GET]
+ Response 200 (application/json)

        [{
          "id": 1, "title": "Jogging in park"
        }, {
          "id": 2, "title": "Pick-up posters from post-office"
        }]

### Create a Note [POST]
+ Request (application/json)

        { "title": "Buy cheese and bread for breakfast." }

+ Response 201 (application/json)

        { "id": 3, "title": "Buy cheese and bread for breakfast." }

## Note [/notes/{id}]
A single Note object with all its details

+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the Note to perform action with. Has example value.

### Retrieve a Note [GET]
+ Response 200 (application/json)

    + Header

            X-My-Header: The Value

    + Body

            { "id": 2, "title": "Pick-up posters from post-office" }

### Remove a Note [DELETE]
+ Response 204

# Group Course Service
  For retrieving course information from CAP.

## Course [/courses/{id}]
   Operations on a specific course.

+ Parameters
  + id (required, int) ... ID of the specific course

### Retrieve course structure [GET]

+ Response 200

        {  
          "id":1,
          "modules":[  
            {  
              "type":"module",
              "name":"Unit 1",
              "id":1,
              "modules":[  
                {  
                  "type":"module",
                  "name":"Lesson 1",
                  "id":2,
                  "modules":[  
                    {  
                      "type":"activityList",
                      "name":"Activity List 1",
                      "id":1,
                      "activities":[  
                        {  
                          "name":"Activity 1",
                          "id":1
                        },
                        {  
                          "name":"Activity 2",
                          "id":2
                        }
                      ]
                    }
                  ]
                },
                {  
                  "type":"module",
                  "name":"Lesson 2",
                  "id":3,
                  "modules":[  
                    {  
                      "type":"activityList",
                      "name":"Activity List 2",
                      "id":2,
                      "activities":[  
                        {  
                          "name":"Activity 3",
                          "id":3
                        },
                        {  
                          "name":"Activity 4",
                          "id":4
                        }
                      ]
                    }
                  ]
                }
              ]
            }
          ]
        }

